#!/usr/bin/env bash
# hoa-admin local DEV environment — one entry point.
#
#   ./dev.sh up      start the local Supabase stack (Docker) and write .env.dev
#   ./dev.sh seed    clone production data into the local stack (read-only on prod)
#   ./dev.sh run     start the admin console on http://localhost:5052 (DEV mode)
#   ./dev.sh reset   wipe the local database, re-apply the schema, re-seed
#   ./dev.sh status  show local stack URLs / keys
#   ./dev.sh down    stop the local stack (data persists in a Docker volume)
#
# Requires: Docker Desktop running, `supabase` CLI (brew install supabase/tap/supabase),
# and the repo venv (../venv or /Users/thomasmasters/Projects/.venv).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/.." && pwd)"
ENV_DEV="$HERE/.env.dev"
PORT="${HOA_DEV_PORT:-5052}"

# Prefer the workspace venv the project docs point at; fall back to a local one.
for cand in /Users/thomasmasters/Projects/.venv/bin/python3 "$REPO/venv/bin/python3"; do
  if [ -x "$cand" ] && "$cand" -c "import flask, supabase, bcrypt, markdown" 2>/dev/null; then PY="$cand"; break; fi
done
: "${PY:?No venv with flask+supabase+bcrypt+markdown found — see README}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing: $1 — $2" >&2; exit 1; }; }

write_env_dev() {
  # supabase status -o env prints API_URL / SERVICE_ROLE_KEY / ANON_KEY … for the local stack.
  local status; status="$(cd "$HERE" && supabase status -o env 2>/dev/null)" || { echo "stack not running — ./dev.sh up" >&2; exit 1; }
  local api_url service_key
  api_url="$(echo "$status" | sed -n 's/^API_URL="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')"
  service_key="$(echo "$status" | sed -n 's/^SERVICE_ROLE_KEY="\{0,1\}\([^"]*\)"\{0,1\}$/\1/p')"
  [ -n "$api_url" ] && [ -n "$service_key" ] || { echo "could not parse supabase status" >&2; echo "$status" >&2; exit 1; }
  # Carry the real OpenAI key over from ../.env so Search / embeddings work — that
  # is the one production "connection point" a local sandbox legitimately shares.
  local openai; openai="$(sed -n 's/^OPENAI_API_KEY=//p' "$REPO/.env" 2>/dev/null | head -1)"
  cat > "$ENV_DEV" <<EOF
# Generated by dev.sh up — local Supabase stack. Safe to regenerate. Do not commit.
HOA_ENV=dev
SUPABASE_URL=$api_url
SUPABASE_SERVICE_ROLE_KEY=$service_key
OPENAI_API_KEY=$openai
SECRET_KEY=local-dev-only-not-a-secret
PORT=$PORT
EOF
  echo "[dev] wrote $ENV_DEV  (API $api_url)"
}

cmd="${1:-help}"
case "$cmd" in
  up)
    need docker "install Docker Desktop and start it"
    need supabase "brew install supabase/tap/supabase"
    docker info >/dev/null 2>&1 || { echo "Docker is not running" >&2; exit 1; }
    (cd "$HERE" && supabase start)
    write_env_dev
    echo "[dev] stack is up. Next: ./dev.sh seed   then   ./dev.sh run"
    ;;
  seed)
    [ -f "$ENV_DEV" ] || write_env_dev
    (cd "$HERE" && "$PY" seed_from_prod.py "${@:2}")
    ;;
  reset)
    need supabase "brew install supabase/tap/supabase"
    (cd "$HERE" && supabase db reset)      # re-applies migrations/ from scratch
    write_env_dev
    (cd "$HERE" && "$PY" seed_from_prod.py --wipe)
    ;;
  run)
    [ -f "$ENV_DEV" ] || write_env_dev
    set -a; . "$ENV_DEV"; set +a
    export HOA_ENV=dev PORT="$PORT"
    case "$SUPABASE_URL" in
      *localhost*|*127.0.0.1*) ;;
      *) echo "REFUSING to run: SUPABASE_URL is not local ($SUPABASE_URL)" >&2; exit 1 ;;
    esac
    echo "[dev] admin console → http://localhost:$PORT  (DEV mode, templates auto-reload)"
    cd "$REPO" && exec "$PY" admin_app.py
    ;;
  status)
    (cd "$HERE" && supabase status)
    ;;
  down)
    (cd "$HERE" && supabase stop)
    ;;
  *)
    sed -n '2,12p' "$0"
    ;;
esac
